// Generated by https://quicktype.io

export interface TaskResponse {
  _id: string;
  title: string;
  description: string;
  status: string;
  priority: string;
  type: string;
  idUser: string;
  createDay: string;
  __v: number;
}
